### PR TITLE
Don't modify a project name supplied by the user.

### LINKED ISSUE #62: User supplied project names are modified
**Describe the bug**
When creating a project, the user can provide a name for that project. Fastpass modifies that name before using it; in particular, the project name gets shortened if it is longer than a certain limit. This might surprise the user, and, more importantly, it breaks interaction with the IntelliJ Pants plugin.

**To Reproduce**
```
VERY_LONG_NAME=$(cat /dev/urandom | tr -cd '[:alnum:]' | head -c 100)
echo $VERY_LONG_NAME
fastpass create --name $VERY_LONG_NAME ::
fastpass list
fastpass info $VERY_LONG_NAME
```

**Expected behavior**
The name of the new project should be exactly as specified by the user.

### PR DESCRIPTION
**Pull request by odisseus**
Fixes #62.

### CODE REVIEW

File: tests/slow/src/test/scala/tests/BloopPantsSuite.scala [hunk 1]
```diff
@@ -51,6 +51,40 @@ class BloopPantsSuite extends FastpassSuite {
...
+                                 |)
+                                 |/src/Main.scala
+                                 |package src
+                                 |object Main extends App {
+                                 |  println(core.Lib.greeting)
+                                 |}
+                                 |""".stripMargin)
+
+    val veryLongName =
+      "This.is.a.very.very.long.project.name.that.contains.exactly.one.hundred.characters_12345678901234567"
```
Comment (Duhemm) [inline tests/slow/src/test/scala/tests/BloopPantsSuite.scala:78]: Can you please verify that things still work when the provided name contains slashes? This is why the previous logic was put into place: https://github.com/scalameta/fastpass/commit/f920ca59550703890897deab48f59d87583ff635

**Review by Duhemm — APPROVED** [review]
LGTM! Can you please add a test for the forward slashes?

File: tests/slow/src/test/scala/tests/BloopPantsSuite.scala (hunk 1 above)
Comment (odisseus) [reply tests/slow/src/test/scala/tests/BloopPantsSuite.scala:78]: I have changed the logic so that the slashes are always replaced.
